export const reviewLexiconV1 = {
  version: "worker-ground-truth-es-419-v1",
  strings: {
    es: {
      loadingNext: "Cargando el siguiente video...",
      noEligible: "No hay videos listos.",
      noChunkAvailable: "No hay videos listos",
      confirmFailed: "No se pudo confirmar",
      confirmed: "piezas guardadas.",
      leaseTitle: "Si te retiras, este video vuelve a estar disponible después de 5 minutos.",
      countingBehind: "revisando con",
      behindLive: "de retraso",
      instruction: "Cuenta una pieza terminada en el primer cuadro en que el trabajador la suelta y la pieza queda en el área de salida indicada.",
      awayWarning: "Si te retiras, este video vuelve a estar disponible después de 5 minutos.",
      seekVideo: "Moverse en el video",
      leftAt: "restantes a",
      pause: "Pausa",
      back10: "10 s",
      endChunk: "Terminar video",
      reportProblem: "Reportar problema",
      problemPrompt: "¿Qué problema tiene el video?",
      cameraBlocked: "Cámara bloqueada",
      timestampJump: "La hora del video salta",
      videoWontPlay: "El video no reproduce",
      wrongStation: "Estación equivocada",
      noUsableFootage: "No hay video utilizable",
      otherProblem: "Otro problema",
      summaryPrefix: "Contaste",
      summaryIn: "en",
      noClicks: "No se registraron clics.",
      confirm: "CONFIRMAR",
      redo: "CONTINUAR VIDEO",
      startNextVideo: "COMENZAR SIGUIENTE VIDEO",
      zeroGuard: "No contaste piezas. ¿Cero piezas, correcto?",
      yes: "Sí",
      no: "No",
      runningTally: "Conteo actual",
      countButton: "+1 PIEZA",
      undo: "Deshacer",
      countHotkey: "conteo",
      undoHotkey: "deshacer",
      backHotkey: "retroceder 10 s",
      play: "Reproducir video",
      playFailed: "No se pudo reproducir el video.",
      speedSteppedDown: "La velocidad no funcionó. El video volvió a 1x.",
      myWorkToday: "Mis videos de hoy",
      todayPrefix: "Hoy:",
      done: "listos",
      left: "por hacer",
      numberHeader: "#",
      stationHeader: "Estación",
      timeHeader: "Hora",
      statusHeader: "Estado",
      countHeader: "Conteo",
      working: "En curso",
      pending: "Por hacer",
      doneStatus: "Listo",
      problemStatus: "Problema",
      languageLabel: "Idioma",
      previousContext: "Contexto del video anterior. No cuentes aquí.",
      nextContext: "Contexto del siguiente video. No cuentes aquí.",
    },
    en: {
      loadingNext: "Loading the next video...",
      noEligible: "No videos are ready.",
      noChunkAvailable: "No videos are ready",
      confirmFailed: "Confirm failed",
      confirmed: "pieces saved.",
      leaseTitle: "If you leave, this video becomes available again after 5 minutes.",
      countingBehind: "counting",
      behindLive: "behind live",
      instruction: "Count one piece on the first frame where the worker has released the finished piece and it remains in the designated output area.",
      awayWarning: "If you step away, this video becomes available again after 5 minutes.",
      seekVideo: "Seek video",
      leftAt: "left at",
      pause: "Pause",
      back10: "10s",
      endChunk: "Finish video",
      reportProblem: "Report problem",
      problemPrompt: "What is wrong with the video?",
      cameraBlocked: "Camera blocked",
      timestampJump: "Video timestamp jumps",
      videoWontPlay: "Video won't play",
      wrongStation: "Wrong station",
      noUsableFootage: "No usable footage",
      otherProblem: "Other",
      summaryPrefix: "You counted",
      summaryIn: "in",
      noClicks: "No clicks recorded.",
      confirm: "CONFIRM",
      redo: "CONTINUE VIDEO",
      startNextVideo: "START NEXT VIDEO",
      zeroGuard: "You counted no pieces. Is zero correct?",
      yes: "Yes",
      no: "No",
      runningTally: "Running tally",
      countButton: "+1 COUNT",
      undo: "Undo",
      countHotkey: "count",
      undoHotkey: "undo",
      backHotkey: "back 10s",
      play: "Play video",
      playFailed: "Video could not be played.",
      speedSteppedDown: "That speed did not work. The video returned to 1x.",
      myWorkToday: "My videos today",
      todayPrefix: "Today:",
      done: "done",
      left: "to do",
      numberHeader: "#",
      stationHeader: "Station",
      timeHeader: "Time",
      statusHeader: "Status",
      countHeader: "Count",
      working: "Working",
      pending: "To do",
      doneStatus: "Done",
      problemStatus: "Problem",
      languageLabel: "Language",
      previousContext: "Context from the previous video. Do not count here.",
      nextContext: "Context from the next video. Do not count here.",
    },
  },
} as const;
