import { reviewLexiconV1 } from "@/lib/reviewLexicon";

export const reviewStrings = {
  es: {
    loadingNext: "Cargando el siguiente bloque...",
    noEligible: "No hay bloques disponibles.",
    noChunkAvailable: "No hay bloques disponibles",
    confirmFailed: "No se pudo confirmar",
    confirmed: "eventos confirmados.",
    leaseTitle: "Si te retiras, este bloque vuelve a la cola después de 5 minutos.",
    countingBehind: "revisando con",
    behindLive: "de retraso",
    instruction: reviewLexiconV1.es.instruction,
    awayWarning: "Si te retiras, este bloque vuelve a la cola después de 5 minutos.",
    seekVideo: "Moverse en el video",
    leftAt: "restantes a",
    pause: "Pausa",
    back10: "10 s",
    endChunk: "Terminar bloque",
    reportProblem: "Reportar problema",
    problemPrompt: "¿Qué problema tiene el video?",
    cameraBlocked: "Cámara bloqueada",
    cannotTell: "No se puede determinar",
    videoWontPlay: "El video no reproduce",
    wrongScene: "Escena equivocada",
    summaryPrefix: "Contaste",
    summaryIn: "en",
    noClicks: "No se registraron clics.",
    confirm: "CONFIRMAR",
    redo: "REVISAR DE NUEVO",
    zeroGuard: "No contaste colocaciones. ¿Cero colocaciones, correcto?",
    yes: "Sí",
    no: "No",
    runningTally: "Conteo actual",
    countButton: reviewLexiconV1.es.countButton,
    undo: "Deshacer",
    countHotkey: "conteo",
    undoHotkey: "deshacer",
    backHotkey: "retroceder 10 s",
    play: "Reproducir video",
    playFailed: "No se pudo reproducir el video.",
    myWorkToday: "Mi trabajo de hoy",
    todayPrefix: "Hoy:",
    done: "listos",
    left: "pendientes",
    numberHeader: "#",
    stationHeader: "Estación",
    timeHeader: "Hora",
    statusHeader: "Estado",
    countHeader: "Conteo",
    working: "En curso",
    pending: "Pendiente",
    lockedByOther: "En revisión",
    doneStatus: "Listo",
    problemStatus: "Problema",
    languageLabel: "Idioma",
  },
  en: {
    loadingNext: "Loading next chunk...",
    noEligible: "No eligible chunks.",
    noChunkAvailable: "No chunk available",
    confirmFailed: "Confirm failed",
    confirmed: "events confirmed.",
    leaseTitle: "If you leave, this chunk returns to the queue after 5 minutes.",
    countingBehind: "counting",
    behindLive: "behind live",
    instruction: reviewLexiconV1.en.instruction,
    awayWarning: "If you step away, this chunk goes back to the queue after 5 minutes.",
    seekVideo: "Seek video",
    leftAt: "left at",
    pause: "Pause",
    back10: "10s",
    endChunk: "End chunk",
    reportProblem: "Report problem",
    problemPrompt: "What is wrong with the video?",
    cameraBlocked: "Camera blocked",
    cannotTell: "Can't tell",
    videoWontPlay: "Video won't play",
    wrongScene: "Wrong scene",
    summaryPrefix: "You counted",
    summaryIn: "in",
    noClicks: "No clicks recorded.",
    confirm: "CONFIRM",
    redo: "REDO",
    zeroGuard: "No placements counted — is that right?",
    yes: "Yes",
    no: "No",
    runningTally: "Running tally",
    countButton: reviewLexiconV1.en.countButton,
    undo: "Undo",
    countHotkey: "count",
    undoHotkey: "undo",
    backHotkey: "back 10s",
    play: "Play video",
    playFailed: "Video could not be played.",
    myWorkToday: "My work today",
    todayPrefix: "Today:",
    done: "done",
    left: "left",
    numberHeader: "#",
    stationHeader: "Station",
    timeHeader: "Time",
    statusHeader: "Status",
    countHeader: "Count",
    working: "Working",
    pending: "Pending",
    lockedByOther: "In review",
    doneStatus: "Done",
    problemStatus: "Problem",
    languageLabel: "Language",
  },
} as const;

export type ReviewLanguage = keyof typeof reviewStrings;
export type ReviewStringSet = (typeof reviewStrings)[ReviewLanguage];
