#!/usr/bin/env bash
set -euo pipefail

FFMPEG="${FFMPEG:-/opt/homebrew/bin/ffmpeg}"
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="${ROOT_DIR}/demo-media"
PALLET_ROOT="/Users/thomas/FactoryVisionArtifacts/onboarding/factory-live-20260626"
GATE_ROOT="/Users/thomas/FactoryVisionArtifacts/onboarding/factory-live-cam2-20260626"

if [[ ! -x "${FFMPEG}" ]]; then
  echo "ffmpeg not found at ${FFMPEG}" >&2
  exit 1
fi

mkdir -p "${OUT_DIR}/pallet-a" "${OUT_DIR}/gate-line"

find_segment() {
  local root="$1"
  local hour="$2"
  local attempt path

  for attempt in 1 2 3; do
    path="$(
      find "${root}" -path "*/segments/*" -type f \( -iname "*.mkv" -o -iname "*.mp4" -o -iname "*.mov" \) 2>/dev/null \
        | sort \
        | awk -v pattern="20260626T${hour}" 'index($0, pattern) { print; exit }'
    )"
    if [[ -n "${path}" && -r "${path}" ]]; then
      printf '%s\n' "${path}"
      return 0
    fi
    sleep 2
  done

  echo "No readable segment found under ${root} for hour ${hour}" >&2
  return 1
}

transcode() {
  local src="$1"
  local dest="$2"

  for attempt in 1 2 3; do
    if "${FFMPEG}" -hide_banner -loglevel error -y \
      -i "${src}" \
      -t 60 \
      -vf "scale=960:-2" \
      -an \
      -c:v libx264 \
      -preset veryfast \
      -crf 26 \
      -movflags +faststart \
      -pix_fmt yuv420p \
      "${dest}"; then
      return 0
    fi
    echo "Retrying ${src} (${attempt}/3)" >&2
    sleep 2
  done

  echo "Failed to transcode ${src}" >&2
  return 1
}

prepare_station() {
  local label="$1"
  local root="$2"
  local slug="$3"
  shift 3
  local buckets=("$@")
  local bucket src dest

  for bucket in "${buckets[@]}"; do
    src="$(find_segment "${root}" "${bucket%%:*}")"
    dest="${OUT_DIR}/${slug}/${bucket#*:}.mp4"
    echo "${label}: ${src} -> ${dest}"
    transcode "${src}" "${dest}"
  done
}

prepare_station "Pallet A" "${PALLET_ROOT}" "pallet-a" \
  "10:morning" \
  "13:midday" \
  "16:afternoon"

prepare_station "Gate line" "${GATE_ROOT}" "gate-line" \
  "10:morning" \
  "13:midday" \
  "16:afternoon"

cat > "${OUT_DIR}/README.md" <<'README'
# Demo Media

Generated by `console/scripts/prepare-demo-media.sh` from local 2026-06-26 factory recordings. MP4 outputs are ignored and are served in development through `/api/media/...`.
README

echo "Demo media ready in ${OUT_DIR}"
